spring.application.name=SKINOTE

# 서버 포트
server.port=8080

# Oracle DB Connection
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=skinote
spring.datasource.password=skinote0315

# MyBatis 자동 카멜케이스 변환 (USER_ID -> userId)
mybatis.configuration.map-underscore-to-camel-case=true
# MyBatis XML 파일이 mappers 폴더 안에 있다고 스프링에게 알려줍니다
mybatis.mapper-locations=classpath:mappers/**/*.xml
# 패키지 내의 마이바티스 SQL 쿼리와 파라미터 로그 출력 설정
logging.level.com.chaewon.skinote=DEBUG