spring.application.name=SKINOTE

# 서버 포트
server.port=8080

# Oracle DB Connection
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=skinote
spring.datasource.password=skinote0315

# MyBatis 자동 카멜케이스 변환 (USER_ID -> userId)
mybatis.configuration.map-underscore-to-camel-case=true